create table if not exists public.user_profiles (
    id uuid primary key references auth.users (id) on delete cascade,
    email text not null unique,
    full_name text,
    avatar_url text,
    provider text default 'google',
    course_level text,
    study_mode text,
    attempt_type text,
    exam_group text,
    strength_area text,
    survey_completed boolean not null default false,
    last_sign_in_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.user_profiles add column if not exists course_level text;
alter table public.user_profiles add column if not exists study_mode text;
alter table public.user_profiles add column if not exists attempt_type text;
alter table public.user_profiles add column if not exists exam_group text;
alter table public.user_profiles add column if not exists strength_area text;
alter table public.user_profiles add column if not exists survey_completed boolean not null default false;

create table if not exists public.user_activity_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users (id) on delete cascade,
    event_type text not null,
    page_url text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.user_state_store (
    user_id uuid not null references auth.users (id) on delete cascade,
    state_key text not null,
    state_value text not null,
    updated_at timestamptz not null default now(),
    primary key (user_id, state_key)
);

create table if not exists public.user_materials (
    id text primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    roadmap_id text not null,
    kind text not null check (kind in ('file', 'link', 'note')),
    title text not null,
    file_path text,
    mime_type text,
    size bigint not null default 0,
    url text,
    note_text text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.touch_user_profile_last_sign_in(p_user_id uuid default auth.uid())
returns void
language plpgsql
as $$
begin
    update public.user_profiles
    set last_sign_in_at = now()
    where id = p_user_id
      and auth.uid() = p_user_id;
end;
$$;

grant execute on function public.touch_user_profile_last_sign_in(uuid) to authenticated;

alter table public.user_profiles
    alter column created_at set default now(),
    alter column updated_at set default now();

alter table public.user_activity_logs
    alter column created_at set default now();

alter table public.user_state_store
    alter column updated_at set default now();

alter table public.user_materials
    alter column created_at set default now(),
    alter column updated_at set default now();

drop trigger if exists user_profiles_set_updated_at on public.user_profiles;

create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row
execute function public.set_updated_at();

drop trigger if exists user_state_store_set_updated_at on public.user_state_store;

create trigger user_state_store_set_updated_at
before update on public.user_state_store
for each row
execute function public.set_updated_at();

drop trigger if exists user_materials_set_updated_at on public.user_materials;

create trigger user_materials_set_updated_at
before update on public.user_materials
for each row
execute function public.set_updated_at();

alter table public.user_profiles enable row level security;
alter table public.user_activity_logs enable row level security;
alter table public.user_state_store enable row level security;
alter table public.user_materials enable row level security;

drop policy if exists "profiles_select_own" on public.user_profiles;
create policy "profiles_select_own"
on public.user_profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.user_profiles;
create policy "profiles_insert_own"
on public.user_profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.user_profiles;
create policy "profiles_update_own"
on public.user_profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "activity_select_own" on public.user_activity_logs;
create policy "activity_select_own"
on public.user_activity_logs
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "activity_insert_own" on public.user_activity_logs;
create policy "activity_insert_own"
on public.user_activity_logs
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "state_select_own" on public.user_state_store;
create policy "state_select_own"
on public.user_state_store
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "state_insert_own" on public.user_state_store;
create policy "state_insert_own"
on public.user_state_store
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "state_update_own" on public.user_state_store;
create policy "state_update_own"
on public.user_state_store
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "state_delete_own" on public.user_state_store;
create policy "state_delete_own"
on public.user_state_store
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "materials_select_own" on public.user_materials;
create policy "materials_select_own"
on public.user_materials
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "materials_insert_own" on public.user_materials;
create policy "materials_insert_own"
on public.user_materials
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "materials_update_own" on public.user_materials;
create policy "materials_update_own"
on public.user_materials
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "materials_delete_own" on public.user_materials;
create policy "materials_delete_own"
on public.user_materials
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists user_activity_logs_user_id_created_at_idx
on public.user_activity_logs (user_id, created_at desc);

create index if not exists user_state_store_user_id_updated_at_idx
on public.user_state_store (user_id, updated_at desc);

create index if not exists user_materials_user_id_roadmap_created_at_idx
on public.user_materials (user_id, roadmap_id, created_at desc);

-- STORAGE SETUP
-- Your current SQL environment does not expose storage.buckets / storage.objects,
-- so create the Storage bucket from the Supabase dashboard UI instead of here.
--
-- Steps:
-- 1. Open Supabase dashboard
-- 2. Go to Storage
-- 3. Create a new bucket named: study-materials
-- 4. Keep the bucket private (not public)
--
-- After the bucket exists, if your project exposes storage policy SQL,
-- you can add storage object policies separately from the dashboard or SQL editor.
